services:
  dell_idrac_fan_controller:
    container_name: Dell_R730xd
    image: ghcr.io/tigerblue77/dell_idrac_fan_controller:v1.11
    restart: unless-stopped
    environment:
      IDRAC_HOST: "10.10.10.105"
      IDRAC_USERNAME: "root"
      IDRAC_PASSWORD: "calvin"
      FAN_SPEED: "60"
      CPU_TEMPERATURE_THRESHOLD: "80"
      CHECK_INTERVAL: "60"
      DISABLE_THIRD_PARTY_PCIE_CARD_DELL_DEFAULT_COOLING_RESPONSE: "true"