services:
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:2.1.5
    restart: unless-stopped
    networks:
      - proxy
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      AUTO_UPDATE: "true" #optional
      DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:prowlarr"
    volumes:
      - "/data/prowlarr/config:/config"
    labels:
      traefik.enable: "true"
      traefik.http.routers.prowlarr.rule: "Host(`prowlarr.comprofix.xyz`)"
      traefik.http.routers.prowlarr.entrypoints: "https"
      traefik.http.routers.prowlarr.tls: "true"
      traefik.http.services.prowlarr.loadbalancer.server.port: "9696"

networks:
  proxy:
    external: true