services:
  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd:4.5.5
    restart: unless-stopped
    networks:
      - proxy
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      HOSTNAME: "sabnzbd.comprofix.xyz"
      DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:sabnzbd"
    volumes:
      - "/data/sabnzbd/config:/config"
      - /mnt/nfs/data:/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.sabnzbd.rule: "Host(`sabnzbd.comprofix.xyz`)"
      traefik.http.routers.sabnzbd.entrypoints: "https"
      traefik.http.routers.sabnzbd.tls: "true"
      traefik.http.services.sabnzbd.loadbalancer.server.port: "8080"

networks:
  proxy:
    external: true