services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:1.35.1
    restart: unless-stopped
    networks:
      - proxy
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      SIGNUPS_ALLOWED: "false"
    volumes:
      - "/data/vaultwarden/data:/data"
    labels:
      traefik.enable: "true"
      traefik.http.routers.vaultwarden.rule: "Host(`vault.comprofix.com`)"
      traefik.http.routers.vaultwarden.entrypoints: "https"
      traefik.http.routers.vaultwarden.tls: "true"
      traefik.http.routers.vaultwarden.service: "vaultwarden"
      traefik.http.services.vaultwarden.loadbalancer.server.port: "80"

  vaultwarden-backup:
    container_name: vaultwardenbackup
    image: ttionya/vaultwarden-backup:1.26.0
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      CRON: "0 4 * * *"
      BACKUP_KEEP_DAYS: "14"
      ZIP_PASSWORD: "${VAULTWARDEN_BACKUP_ZIP_PASSWORD}"
    volumes:
      - "/data/vaultwarden/data:/bitwarden/data"
      - "/data/vaultwardenbackup/config:/config"

networks:
  proxy:
    external: true
