services:
  gotify:
    image: gotify/server:2.7.3
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /data/gotify/data:/app/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.gotify.rule: "Host(`gotify.comprofix.com`)"
      traefik.http.routers.gotify.entrypoints: "https"
      traefik.http.routers.gotify.tls: "true"
      traefik.http.routers.gotify.service: "gotify"
      traefik.http.services.gotify.loadbalancer.server.port: "80"

networks:
  proxy:
    external: true