services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:v1.6.1
    restart: unless-stopped
    networks:
      - name: proxy
    environment:
      LOG_LEVEL: debug
      HOMEPAGE_ALLOWED_HOSTS: homepage.comprofix.xyz
    volumes:
      - "/data/homepage/config:/app/config"
      - "/data/dashboard-icons:/app/public/icons"
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: "true"
      traefik.http.routers.homepage.rule: "Host(`homepage.comprofix.xyz`)"
      traefik.http.routers.homepage.entrypoints: "https"
      traefik.http.routers.homepage.tls: "true"
      traefik.http.routers.homepage.service: "homepage"
      traefik.http.services.homepage.loadbalancer.server.port: "3000"

networks:
  proxy:
    external: true