services:
  lidarr:
    container_name: lidarr
    image: ghcr.io/linuxserver/lidarr:8.1.2135
    restart: unless-stopped
    networks:
      - proxy
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      AUTO_UPDATE: "true" #optional
      DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:lidarr"
    volumes:
      - "/data/lidarr/config:/config"
      - /mnt/nfs/data:/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.lidarr.rule: "Host(`lidarr.comprofix.xyz`)"
      traefik.http.routers.lidarr.entrypoints: "https"
      traefik.http.routers.lidarr.tls: "true"
      traefik.http.services.lidarr.loadbalancer.server.port: "8686"

networks:
  proxy:
    external: true  