services:
  pykms:
    container_name: pykms
    image: ghcr.io/py-kms-organization/py-kms:latest@sha256:6a8c012e016efea611bf465713bbc08a36b4bfb2e60115e4481f6bb6b9f5b2a4
    restart: unless-stopped
    ports:
      - "1688:1688"
    environment:
      IP: "0.0.0.0"
      SQLITE: "true"
      HWID: "RANDOM"
      LOGLEVEL: "INFO"
    volumes:
      - "/data/pykms/db:/home/py-kms/db"
      - /etc/localtime:/etc/localtime:ro

